### ISSUE TITLE
Violating the license and missing the copyright

### ISSUE THREAD

**Issue by skydoves** [rahulsain/Scribble.io-Kotlin#1]
Hey, @rahulsain, You're copying the entire source code and violating the license - you've uploaded the application with a few tweaks using the Stream chat development API key. Please note somewhere you're using [Stream-draw-android](https://github.com/GetStream/stream-draw-android) open-source project. Thanks!

**Comment by rahulsain** [comment]
Hello @skydoves,

Thank you for bringing this to my attention. I apologize for any infringement of the [Stream-draw-android](https://github.com/GetStream/stream-draw-android) open-source project license.

I will make the necessary changes to the license and ensure that proper attribution is given. Additionally, I will replace the Stream chat development API key and make the required changes to the codebase to ensure compliance with the open-source project's licensing terms.

However, I am currently busy with professional commitments, and it might take me some time to make these changes. But rest assured, I will take the necessary steps as soon as possible. Thank you for your understanding and patience.

**Comment by skydoves** [comment]
All good, and thanks for replying to this! Feel free to reach out to me if you have any problems connecting Stream chat SDK!

**Comment by rahulsain** [comment]
Thank you for your understanding and support! I appreciate your willingness to assist me in connecting the Stream chat SDK. I will definitely reach out to you if I encounter any issues.

Thanks again for bringing this to my attention and for your kind offer to help.
